### ISSUE TITLE
InvalidParameterException when running sls cognito deploy -s dev -r us-east-1

### ISSUE THREAD

**Issue by calam1** [trek10inc/serverless-cognito-manager#4]
trying to deploy, I ran the following command:  sls cognito deploy -s dev -r us-east-1 --debug

I received the InvalidParameterException, I tried this on serverless 0.5.5, I upgraded to 0.5.6 thinking it may resolve the issue; but same error.  Any clues to what I may need to do???

I am presently running a custom lambda from Cloudformation to create my user and identity pools, but like what you guys are doing better than my solution.

```
Serverless: WARNING: This variable is not defined: cognitoUserIdentityPoolClientId
Serverless: WARNING: This variable is not defined: cognitoUserIdentityPoolId
Serverless: WARNING: This variable is not defined: cognitoAuthenticatedRole
Serverless: WARNING: This variable is not defined: cognitoUnauthenticatedRole
Serverless: WARNING: This variable is not defined: cognitoUserIdentityPoolId
Serverless: Run: serverless cognito deploy -s dev -r us-east-1
Error: { [InvalidParameterException: Required custom attributes are not supported currently.]
  message: 'Required custom attributes are not supported currently.',
  code: 'InvalidParameterException',
  time: Sun Jun 26 2016 09:18:43 GMT-0500 (CDT),
  requestId: 'e30b1f1e-3ba8-11e6-84ce-bbbb4c899843',
  statusCode: 400,
  retryable: false,
  retryDelay: 15.92952434439212 }
```

**Comment by shortjared** [comment]
So sorry for the late reply, github didn't send me a notification. I will look into this more over the next couple days. Thank you for the detailed issue.

**Comment by jchuang1** [comment]
I got the same error and tracked it down to a '-' in our project name that is not accepted by Fed Identity pool.  However, in the CustomAttributes, when rhe "required" field is set to true, it would give the InvalidParameterException error.
